# Theme settings
doks:
    baseurl: "https://dssoc.github.io"
    url: "https://dssoc.github.io"
    color_theme: blue

    header:
        logo:
            text: Data Science & Society
            image: true
        nav:
            - item_name: Course Description
              item_url: '/course'
            - item_name: Schedule
              item_url: '/schedule'
            - item_name: References
              item_url: '/references'
    footer:
        content:
            logo:
                text: Data Science & Society
                image:
            copyright: Copyright &copy; 2017. - Project name <br>All rights reserved.
        social_list:
            - network_name: twitter
              profile_url: '#'
            - network_name: youtube
              profile_url: '#'


# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
